-- ============================================================
-- SEED DATA: 10 Realistic Dummy Leads
-- Run this in Supabase SQL Editor after creating the schema.
-- ============================================================

-- Step 1: Seed master_options for dropdowns
INSERT INTO master_options (option_type, label, value) VALUES
  -- Categories
  ('category', 'Hot Lead', 'HOT LEAD'),
  ('category', 'Warm Lead', 'WARM LEAD'),
  ('category', 'Cold Lead', 'COLD LEAD'),
  -- BU Revenue
  ('bu_revenue', 'WNW', 'WNW'),
  ('bu_revenue', 'WNS', 'WNS'),
  ('bu_revenue', 'UK', 'UK'),
  ('bu_revenue', 'TEP', 'TEP'),
  ('bu_revenue', 'CREATIVE', 'CREATIVE'),
  -- Status
  ('status', 'Lead Masuk', 'Lead Masuk'),
  ('status', 'Estimasi Project', 'Estimasi Project'),
  ('status', 'Proposal Sent', 'Proposal Sent'),
  ('status', 'Closed Won', 'Closed Won'),
  ('status', 'Closed Lost', 'Closed Lost')
ON CONFLICT DO NOTHING;


-- Step 2: Insert 10 Dummy Leads
INSERT INTO leads (
  manual_id,
  date_lead_received,
  company_name,
  main_company,
  project_name,
  bu_revenue,
  category,
  status,
  estimated_revenue,
  nominal_konfirmasi,
  pic_sales,
  account_manager,
  source_lead,
  grade_lead,
  number_of_pax,
  venue_hotel,
  location_city,
  nationality,
  is_onsite,
  is_online,
  contact_full_name,
  contact_email,
  contact_mobile,
  job_title,
  salutation,
  remark,
  follow_up_1,
  month_event,
  year_lead_receive,
  sector,
  is_qualified
) VALUES

-- ========================
-- 3x STATUS: Lead Masuk
-- ========================
(
  1,
  '2026-02-17T09:00:00+07:00',
  'PT Pertamina',
  'Pertamina Group',
  'Annual Safety Gathering 2026',
  'WNW',
  'HOT LEAD',
  'Lead Masuk',
  500000000,
  NULL,
  'Budi Santoso',
  'Rina Wati',
  'Referral',
  'A',
  350,
  'The Westin Resort Nusa Dua',
  'Bali',
  'Indonesia',
  true,
  false,
  'Eko Prasetyo',
  'eko.prasetyo@pertamina.com',
  '08123456001',
  'VP Corporate Affairs',
  'Mr.',
  'Klien minta venue di Bali, budget flexible.',
  '17 Feb: Email intro sent, awaiting response.',
  'March',
  2026,
  'Oil & Gas',
  true
),
(
  2,
  '2026-02-15T10:30:00+07:00',
  'Bank Mandiri',
  'Mandiri Group',
  'Mandiri Executive Leadership Program',
  'TEP',
  'COLD LEAD',
  'Lead Masuk',
  150000000,
  NULL,
  'Siti Aminah',
  'Dedi Kurniawan',
  'Website Inquiry',
  'B',
  80,
  'TBD',
  'Jakarta',
  'Indonesia',
  true,
  true,
  'Diana Kartika',
  'diana.kartika@bankmandiri.co.id',
  '08123456002',
  'Head of Learning & Development',
  'Mrs.',
  'Perlu follow up minggu depan, budget belum pasti.',
  '15 Feb: Received inquiry via website form.',
  'April',
  2026,
  'Banking & Finance',
  false
),
(
  3,
  '2026-02-13T14:00:00+07:00',
  'Telkomsel',
  'Telkom Group',
  'Digital Innovation Summit 2026',
  'CREATIVE',
  'WARM LEAD',
  'Lead Masuk',
  750000000,
  NULL,
  'Rudi Hartono',
  'Lina Marlina',
  'LinkedIn',
  'A',
  500,
  'ICE BSD',
  'Tangerang',
  'Indonesia',
  true,
  true,
  'Fajar Nugroho',
  'fajar.nugroho@telkomsel.co.id',
  '08123456003',
  'Director of Digital Transformation',
  'Mr.',
  'Event besar, hybrid format. Butuh creative concept.',
  '13 Feb: Initial call, very interested.',
  'May',
  2026,
  'Telecommunications',
  true
),

-- ========================
-- 3x STATUS: Estimasi Project
-- ========================
(
  4,
  '2026-02-10T08:00:00+07:00',
  'Unilever Indonesia',
  'Unilever',
  'Product Launch: New Skincare Line',
  'WNW',
  'HOT LEAD',
  'Estimasi Project',
  1200000000,
  NULL,
  'Dewi Lestari',
  'Agus Permana',
  'Repeat Client',
  'A+',
  200,
  'Raffles Jakarta',
  'Jakarta',
  'Multinational',
  true,
  false,
  'Sarah Johnson',
  'sarah.johnson@unilever.com',
  '08123456004',
  'Brand Manager - Skincare',
  'Ms.',
  'Proposal draft sudah dikirim, menunggu revisi budget.',
  '10 Feb: Sent initial proposal.',
  'April',
  2026,
  'FMCG',
  true
),
(
  5,
  '2026-02-08T11:00:00+07:00',
  'Gojek',
  'GoTo Group',
  'Gojek Driver Appreciation Day',
  'UK',
  'WARM LEAD',
  'Estimasi Project',
  350000000,
  NULL,
  'Andi Wijaya',
  'Budi Santoso',
  'Cold Call',
  'B',
  1000,
  'Senayan Sports Complex',
  'Jakarta',
  'Indonesia',
  true,
  false,
  'Kevin Aluwi',
  'kevin.a@gojek.com',
  '08123456005',
  'Head of Community',
  'Mr.',
  'Large scale outdoor event, budget sedang dinegosiasi.',
  '8 Feb: Presented concept deck.',
  'March',
  2026,
  'Technology',
  true
),
(
  6,
  '2026-02-06T09:30:00+07:00',
  'Tokopedia',
  'GoTo Group',
  'Merchant Gathering Surabaya',
  'WNS',
  'COLD LEAD',
  'Estimasi Project',
  180000000,
  NULL,
  'Maya Sari',
  'Rina Wati',
  'Event Partnership',
  'C',
  150,
  'Shangri-La Surabaya',
  'Surabaya',
  'Indonesia',
  true,
  false,
  'Rizky Pratama',
  'rizky.pratama@tokopedia.com',
  '08123456006',
  'Regional Manager - East Java',
  'Mr.',
  'Sedang cari alternatif tanggal, venue sudah ok.',
  '6 Feb: Venue visit scheduled.',
  'March',
  2026,
  'E-Commerce',
  false
),

-- ========================
-- 2x STATUS: Closed Won
-- ========================
(
  7,
  '2026-01-25T10:00:00+07:00',
  'BCA',
  'Djarum Group',
  'BCA Prioritas Gala Dinner',
  'TEP',
  'HOT LEAD',
  'Closed Won',
  2000000000,
  1850000000,
  'Budi Santoso',
  'Agus Permana',
  'Repeat Client',
  'A+',
  300,
  'The Mulia Bali',
  'Bali',
  'Indonesia',
  true,
  false,
  'Jahja Setiaatmadja',
  'jahja.s@bca.co.id',
  '08123456007',
  'EVP Marketing',
  'Mr.',
  'Contract signed. Deposit received 28 Jan. Prep underway.',
  '25 Jan: Contract negotiation started.',
  'March',
  2026,
  'Banking & Finance',
  true
),
(
  8,
  '2026-01-20T14:00:00+07:00',
  'Astra International',
  'Astra Group',
  'Astra Management Retreat 2026',
  'WNW',
  'WARM LEAD',
  'Closed Won',
  850000000,
  800000000,
  'Rudi Hartono',
  'Lina Marlina',
  'Direct Request',
  'A',
  120,
  'Padma Resort Ubud',
  'Bali',
  'Indonesia',
  true,
  false,
  'Imam Santoso',
  'imam.santoso@astra.co.id',
  '08123456008',
  'CHRO',
  'Mr.',
  'SPK signed. Vendor coordination in progress.',
  '20 Jan: Presented 3 concept options.',
  'February',
  2026,
  'Automotive & Conglomerate',
  true
),

-- ========================
-- 2x STATUS: Closed Lost
-- ========================
(
  9,
  '2026-01-18T09:00:00+07:00',
  'Shopee Indonesia',
  'Sea Group',
  'Shopee 3.3 Campaign Launch',
  'CREATIVE',
  'HOT LEAD',
  'Closed Lost',
  600000000,
  NULL,
  'Siti Aminah',
  'Dedi Kurniawan',
  'Referral',
  'B',
  400,
  'JCC Senayan',
  'Jakarta',
  'Indonesia',
  true,
  true,
  'Maria Tanoto',
  'maria.tanoto@shopee.co.id',
  '08123456009',
  'Marketing Director',
  'Ms.',
  'LOST: Budget cut by HQ Singapore. Client postponed to Q3.',
  '18 Jan: Initial meeting went well.',
  'February',
  2026,
  'E-Commerce',
  true
),
(
  10,
  '2026-01-15T16:00:00+07:00',
  'Traveloka',
  'Traveloka Group',
  'Traveloka Partner Conference 2026',
  'UK',
  'COLD LEAD',
  'Closed Lost',
  450000000,
  NULL,
  'Andi Wijaya',
  'Rina Wati',
  'LinkedIn',
  'C',
  250,
  'Pullman Jakarta',
  'Jakarta',
  'Indonesia',
  true,
  true,
  'Henrik Nordstrom',
  'henrik.n@traveloka.com',
  '08123456010',
  'VP Partnerships',
  'Mr.',
  'LOST: Competitor offered 30% lower. Client chose other vendor.',
  '15 Jan: Submitted RFP response.',
  'March',
  2026,
  'Travel & Hospitality',
  false
);
