import jsPDF from "jspdf"
import type { Lead } from "@/types"

// ─── Types ────────────────────────────────────────────────────
interface LeadNote {
    id: string
    content: string
    author_name: string | null
    created_at: string
}

interface LeadActivity {
    id: string
    action_type: string
    description: string | null
    field_name: string | null
    old_value: string | null
    new_value: string | null
    created_at: string
    user_name?: string | null
}

export interface ExportLeadPDFOptions {
    lead: Lead & { pipeline?: { name: string } | null }
    notes?: LeadNote[]
    activities?: LeadActivity[]
    currencyFormat?: (value: number) => string
    companyLabel?: string
}

// ─── Theme constants (matches app brand) ──────────────────────
const COLORS = {
    brand: [2, 55, 141] as const,      // #02378D
    text: [26, 29, 31] as const,       // #1a1d1f
    muted: [100, 116, 139] as const,   // slate-500
    light: [148, 163, 184] as const,   // slate-400
    border: [226, 232, 240] as const,  // slate-200
    bgSoft: [248, 250, 252] as const,  // slate-50
}

const FONT = {
    heading: 16,
    sectionTitle: 11,
    label: 9,
    value: 10,
    small: 8,
    micro: 7,
}

const PAGE = {
    marginX: 15,
    marginTop: 18,
    marginBottom: 20,
    lineHeight: 4.5,
    sectionGap: 6,
}

// ─── Helpers ──────────────────────────────────────────────────
function stripHtml(html: string | null | undefined): string {
    if (!html) return ""
    return html
        .replace(/<br\s*\/?>/gi, "\n")
        .replace(/<\/p>/gi, "\n")
        .replace(/<\/li>/gi, "\n")
        .replace(/<li[^>]*>/gi, "• ")
        .replace(/<[^>]+>/g, "")
        .replace(/&nbsp;/g, " ")
        .replace(/&amp;/g, "&")
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/\n{3,}/g, "\n\n")
        .trim()
}

function formatDate(v: string | null | undefined): string {
    if (!v) return "—"
    try {
        return new Date(v).toLocaleDateString("en-GB", {
            day: "numeric",
            month: "short",
            year: "numeric",
        })
    } catch {
        return v
    }
}

function formatDateTime(v: string | null | undefined): string {
    if (!v) return "—"
    try {
        const d = new Date(v)
        return (
            d.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" }) +
            " · " +
            d.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })
        )
    } catch {
        return v
    }
}

// ─── Main exporter ────────────────────────────────────────────
export function exportLeadPdf(opts: ExportLeadPDFOptions): void {
    const { lead, notes = [], activities = [], currencyFormat, companyLabel = "Werkudara Group" } = opts

    const fmt = currencyFormat ?? ((v: number) => `IDR ${v.toLocaleString("id-ID")}`)

    const doc = new jsPDF({ unit: "mm", format: "a4" })
    const pageW = doc.internal.pageSize.getWidth()
    const pageH = doc.internal.pageSize.getHeight()
    const contentW = pageW - PAGE.marginX * 2

    let y = PAGE.marginTop
    let pageNum = 1

    // ── Helpers that close over `doc` and `y` ──
    const ensureSpace = (needed: number) => {
        if (y + needed > pageH - PAGE.marginBottom) {
            addFooter()
            doc.addPage()
            pageNum++
            y = PAGE.marginTop
        }
    }

    const addFooter = () => {
        doc.setFont("helvetica", "normal")
        doc.setFontSize(FONT.micro)
        doc.setTextColor(...COLORS.light)
        doc.text(
            `Generated by LeadEngine · ${companyLabel} · ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}`,
            PAGE.marginX,
            pageH - 8
        )
        doc.text(`Page ${pageNum}`, pageW - PAGE.marginX, pageH - 8, { align: "right" })
    }

    // ── Document Header (top band) ──
    doc.setFillColor(...COLORS.brand)
    doc.rect(0, 0, pageW, 11, "F")
    doc.setFont("helvetica", "bold")
    doc.setFontSize(10)
    doc.setTextColor(255, 255, 255)
    doc.text("LEAD SUMMARY", PAGE.marginX, 7.2)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(8)
    doc.text(companyLabel, pageW - PAGE.marginX, 7.2, { align: "right" })

    y = PAGE.marginTop

    // ── Project Header ──
    doc.setFont("helvetica", "bold")
    doc.setFontSize(FONT.heading)
    doc.setTextColor(...COLORS.text)
    const titleLines = doc.splitTextToSize(lead.project_name || "Untitled Lead", contentW)
    titleLines.forEach((line: string) => {
        doc.text(line, PAGE.marginX, y)
        y += 6
    })

    // Subtitle row — pipeline · stage · grade
    const subtitleParts: string[] = []
    if (lead.pipeline?.name) subtitleParts.push(lead.pipeline.name)
    if (lead.pipeline_stage?.name) subtitleParts.push(lead.pipeline_stage.name)
    if (lead.grade_lead) subtitleParts.push(`Grade ${lead.grade_lead}`)
    if (lead.category) subtitleParts.push(lead.category)
    if (subtitleParts.length) {
        doc.setFont("helvetica", "normal")
        doc.setFontSize(FONT.small)
        doc.setTextColor(...COLORS.muted)
        doc.text(subtitleParts.join("  ·  "), PAGE.marginX, y)
        y += 6
    }

    // Divider
    doc.setDrawColor(...COLORS.border)
    doc.setLineWidth(0.2)
    doc.line(PAGE.marginX, y, pageW - PAGE.marginX, y)
    y += 6

    // ── Section renderer ──
    const section = (title: string) => {
        ensureSpace(14)
        doc.setFont("helvetica", "bold")
        doc.setFontSize(FONT.sectionTitle)
        doc.setTextColor(...COLORS.brand)
        // Accent bar
        doc.setFillColor(...COLORS.brand)
        doc.rect(PAGE.marginX, y - 3.5, 1.2, 4.5, "F")
        doc.text(title, PAGE.marginX + 3, y)
        y += PAGE.sectionGap
    }

    // Two-column field row
    const fieldRow = (
        pairs: Array<{ label: string; value: string }>,
    ) => {
        const colW = contentW / 2
        for (let i = 0; i < pairs.length; i += 2) {
            const left = pairs[i]
            const right = pairs[i + 1]

            const leftValLines = left ? doc.splitTextToSize(left.value || "—", colW - 4) : []
            const rightValLines = right ? doc.splitTextToSize(right.value || "—", colW - 4) : []
            const rowHeight = Math.max(leftValLines.length, rightValLines.length) * PAGE.lineHeight + 2.5
            ensureSpace(rowHeight + 3)

            // Labels
            doc.setFont("helvetica", "bold")
            doc.setFontSize(FONT.label)
            doc.setTextColor(...COLORS.muted)
            if (left) doc.text(left.label.toUpperCase(), PAGE.marginX, y)
            if (right) doc.text(right.label.toUpperCase(), PAGE.marginX + colW, y)
            y += 4

            // Values
            doc.setFont("helvetica", "normal")
            doc.setFontSize(FONT.value)
            doc.setTextColor(...COLORS.text)
            if (leftValLines.length) {
                leftValLines.forEach((line: string, idx: number) => {
                    doc.text(line, PAGE.marginX, y + idx * PAGE.lineHeight)
                })
            }
            if (rightValLines.length) {
                rightValLines.forEach((line: string, idx: number) => {
                    doc.text(line, PAGE.marginX + colW, y + idx * PAGE.lineHeight)
                })
            }
            y += Math.max(leftValLines.length, rightValLines.length) * PAGE.lineHeight + 3
        }
    }

    // Long text block (for brief, SOW, remarks)
    const longText = (text: string) => {
        if (!text) {
            doc.setFont("helvetica", "italic")
            doc.setFontSize(FONT.small)
            doc.setTextColor(...COLORS.light)
            ensureSpace(6)
            doc.text("(empty)", PAGE.marginX, y)
            y += 5
            return
        }
        doc.setFont("helvetica", "normal")
        doc.setFontSize(FONT.value)
        doc.setTextColor(...COLORS.text)
        const lines = doc.splitTextToSize(text, contentW)
        lines.forEach((line: string) => {
            ensureSpace(PAGE.lineHeight + 1)
            doc.text(line, PAGE.marginX, y)
            y += PAGE.lineHeight
        })
        y += 2
    }

    // ── DEAL INFORMATION ──
    section("Deal Information")
    fieldRow([
        { label: "Subsidiary", value: lead.company?.name ?? "—" },
        { label: "Amount", value: lead.estimated_value != null ? fmt(lead.estimated_value) : "—" },
        { label: "Close Date", value: formatDate(lead.target_close_date) },
        { label: "PIC Sales", value: lead.pic_sales_profile?.full_name ?? "—" },
        { label: "Account Manager", value: lead.account_manager_profile?.full_name ?? "—" },
        { label: "Lead Source", value: lead.lead_source ?? "—" },
        { label: "Main Stream", value: lead.main_stream ?? "—" },
        { label: "Stream Type", value: lead.stream_type ?? "—" },
        { label: "Business Purpose", value: lead.business_purpose ?? "—" },
        { label: "Event Format", value: lead.event_format ?? "—" },
    ])

    // ── CLIENT & CONTACT ──
    section("Client & Contact")
    fieldRow([
        { label: "Client Company", value: lead.client_company?.name ?? "—" },
        { label: "Contact Person", value: lead.contact?.full_name ?? "—" },
        { label: "Email", value: lead.contact?.email ?? "—" },
        { label: "Phone", value: lead.contact?.phone ?? "—" },
    ])

    // ── EVENT DETAILS ──
    const hasEventData = lead.event_date_start || lead.event_date_end || (lead.event_dates && lead.event_dates.length) || lead.pax_count || (lead.destinations && lead.destinations.length)
    if (hasEventData) {
        section("Event Details")
        const datePairs: Array<{ label: string; value: string }> = []
        if (lead.event_date_start || lead.event_date_end) {
            datePairs.push({ label: "Event Start", value: formatDate(lead.event_date_start) })
            datePairs.push({ label: "Event End", value: formatDate(lead.event_date_end) })
        }
        if (lead.event_dates && lead.event_dates.length) {
            datePairs.push({ label: "Event Dates", value: lead.event_dates.map(d => formatDate(d)).join(", ") })
        }
        if (lead.pax_count != null) datePairs.push({ label: "Pax Count", value: String(lead.pax_count) })
        if (lead.virtual_platform) datePairs.push({ label: "Virtual Platform", value: lead.virtual_platform })
        if (datePairs.length) fieldRow(datePairs)

        if (lead.destinations && lead.destinations.length) {
            ensureSpace(8)
            doc.setFont("helvetica", "bold")
            doc.setFontSize(FONT.label)
            doc.setTextColor(...COLORS.muted)
            doc.text("DESTINATIONS", PAGE.marginX, y)
            y += 4
            doc.setFont("helvetica", "normal")
            doc.setFontSize(FONT.value)
            doc.setTextColor(...COLORS.text)
            lead.destinations.forEach((d) => {
                const line = d.venue ? `• ${d.city} — ${d.venue}` : `• ${d.city}`
                ensureSpace(PAGE.lineHeight + 1)
                doc.text(line, PAGE.marginX, y)
                y += PAGE.lineHeight
            })
            y += 2
        }
    }

    // ── LOST/WON CONTEXT ──
    if (lead.closed_won_date || lead.closed_lost_date || lead.lost_reason) {
        section("Outcome")
        const outcomePairs: Array<{ label: string; value: string }> = []
        if (lead.closed_won_date) outcomePairs.push({ label: "Closed Won", value: formatDate(lead.closed_won_date) })
        if (lead.closed_lost_date) outcomePairs.push({ label: "Closed Lost", value: formatDate(lead.closed_lost_date) })
        if (lead.lost_reason) outcomePairs.push({ label: "Lost Reason", value: lead.lost_reason })
        if (outcomePairs.length) fieldRow(outcomePairs)
        if (lead.lost_reason_details) {
            ensureSpace(6)
            doc.setFont("helvetica", "bold")
            doc.setFontSize(FONT.label)
            doc.setTextColor(...COLORS.muted)
            doc.text("LOST REASON DETAILS", PAGE.marginX, y)
            y += 4
            longText(lead.lost_reason_details)
        }
    }

    // ── GENERAL BRIEF ──
    section("General Brief & Inquiry")
    longText(stripHtml(lead.general_brief))

    // ── PRODUCTION SOW ──
    section("Production SOW & Equipment")
    longText(stripHtml(lead.production_sow))

    // ── SPECIAL REMARKS ──
    section("Special Remarks")
    longText(stripHtml(lead.special_remarks))

    // ── NOTES (recent 10) ──
    if (notes.length > 0) {
        section(`Notes (${notes.length > 10 ? `latest 10 of ${notes.length}` : notes.length})`)
        notes.slice(0, 10).forEach((n) => {
            ensureSpace(12)
            // Author + date
            doc.setFont("helvetica", "bold")
            doc.setFontSize(FONT.small)
            doc.setTextColor(...COLORS.text)
            doc.text(n.author_name || "Unknown", PAGE.marginX, y)
            doc.setFont("helvetica", "normal")
            doc.setTextColor(...COLORS.light)
            doc.text(formatDateTime(n.created_at), pageW - PAGE.marginX, y, { align: "right" })
            y += 4
            // Content
            const content = stripHtml(n.content)
            if (content) {
                doc.setFontSize(FONT.value)
                doc.setTextColor(...COLORS.text)
                const lines = doc.splitTextToSize(content, contentW)
                lines.forEach((line: string) => {
                    ensureSpace(PAGE.lineHeight + 1)
                    doc.text(line, PAGE.marginX, y)
                    y += PAGE.lineHeight
                })
            }
            y += 3
        })
    }

    // ── ACTIVITY TIMELINE (recent 10) ──
    if (activities.length > 0) {
        section(`Activity Timeline (${activities.length > 10 ? `latest 10 of ${activities.length}` : activities.length})`)
        activities.slice(0, 10).forEach((a) => {
            ensureSpace(7)
            const description = a.description || a.action_type
            const userName = a.user_name || "System"

            doc.setFont("helvetica", "normal")
            doc.setFontSize(FONT.value)
            doc.setTextColor(...COLORS.text)
            // Bullet
            doc.setFillColor(...COLORS.brand)
            doc.circle(PAGE.marginX + 1, y - 1.2, 0.8, "F")

            const bodyText = `${userName} · ${description}`
            const lines = doc.splitTextToSize(bodyText, contentW - 6)
            lines.forEach((line: string, idx: number) => {
                doc.text(line, PAGE.marginX + 4, y + idx * PAGE.lineHeight)
            })
            y += lines.length * PAGE.lineHeight

            doc.setFont("helvetica", "normal")
            doc.setFontSize(FONT.micro)
            doc.setTextColor(...COLORS.light)
            doc.text(formatDateTime(a.created_at), PAGE.marginX + 4, y)
            y += 5
        })
    }

    // ── METADATA FOOTER (last page) ──
    ensureSpace(14)
    y += 2
    doc.setDrawColor(...COLORS.border)
    doc.line(PAGE.marginX, y, pageW - PAGE.marginX, y)
    y += 4
    doc.setFont("helvetica", "normal")
    doc.setFontSize(FONT.micro)
    doc.setTextColor(...COLORS.light)
    const metaPairs = [
        lead.created_at ? `Created: ${formatDateTime(lead.created_at)}` : null,
        lead.updated_at ? `Updated: ${formatDateTime(lead.updated_at)}` : null,
        `Lead ID: ${lead.id}`,
    ].filter(Boolean)
    doc.text(metaPairs.join("  ·  "), PAGE.marginX, y)

    // Footer on current page
    addFooter()

    // ── Save ──
    const safeName = (lead.project_name || "lead")
        .replace(/[^\w\s-]/g, "")
        .replace(/\s+/g, "-")
        .slice(0, 40)
    const dateStamp = new Date().toISOString().slice(0, 10)
    doc.save(`${safeName}_${lead.id}_${dateStamp}.pdf`)
}
