/**
 * Generate the icon components both apps use from Material Symbols.
 *
 * Why generated, and why per app: Material Symbols ships 7,800 SVG files; a
 * font would be megabytes; an SVG loader would need bundler configuration in
 * two apps. Instead this script reads only the symbols named in map.json,
 * inlines their path data, and writes one tree-shakeable module into each
 * app. The output is committed, so deploys need neither this script nor the
 * symbols package.
 *
 * The export names stay Lucide's (Plus, Trash2, Loader2, …) on purpose: the
 * 200-odd files that draw icons changed only their import specifier when the
 * library was swapped, and nothing else. map.json is the one place the two
 * vocabularies meet.
 *
 * Usage: node scripts/icons/generate.mjs
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, "..", "..")
const symbolsDir = path.join(root, "node_modules", "@material-symbols", "svg-400", "rounded")
const lucideDir = path.join(root, "node_modules", "lucide-react", "dist", "esm", "icons")
const map = JSON.parse(fs.readFileSync(path.join(here, "map.json"), "utf8"))
const apps = ["leadengine", "sales-mission"]

// Every name any app imports from the icon module, so the map cannot drift.
const used = new Set()
for (const app of apps) {
  walk(path.join(root, "apps", app), (file) => {
    const source = fs.readFileSync(file, "utf8")
    const pattern = /import\s*(?:type\s*)?\{([^}]*)\}\s*from\s*['"](?:lucide-react|@\/components\/icons)['"]/gs
    for (const match of source.matchAll(pattern)) {
      for (const part of match[1].split(",")) {
        const name = part.trim().replace(/^type\s+/, "").split(/\s+as\s+/)[0].trim()
        if (name) used.add(name)
      }
    }
  })
}
used.delete("LucideIcon")
used.delete("IconComponent")
used.delete("IconProps")

const missing = [...used].filter((name) => !(name in map.symbols) && !(name in map.brands))
if (missing.length) {
  console.error("Icons used but not in map.json:", missing.join(", "))
  process.exit(1)
}

const lines = []
lines.push(`/* eslint-disable */`)
lines.push(`// GENERATED by scripts/icons/generate.mjs from Material Symbols Rounded (Apache-2.0).`)
lines.push(`// Do not edit by hand: change scripts/icons/map.json and run the generator.`)
lines.push(`import { forwardRef, type SVGProps } from "react"`)
lines.push(``)
lines.push(`export interface IconProps extends SVGProps<SVGSVGElement> {`)
lines.push(`  /** Pixel size when no width/height class is set. Tailwind height and width classes still win. */`)
lines.push(`  size?: number | string`)
lines.push(`  /** Accepted for source compatibility with stroke icons; Material Symbols are filled shapes, so it does nothing. */`)
lines.push(`  strokeWidth?: number | string`)
lines.push(`  absoluteStrokeWidth?: boolean`)
lines.push(`}`)
lines.push(`export type IconComponent = ReturnType<typeof symbol>`)
lines.push(`/** The old name for the icon component type, kept so prop types written against Lucide still compile. */`)
lines.push(`export type LucideIcon = IconComponent`)
lines.push(``)
lines.push(`function symbol(name: string, paths: string[]) {`)
lines.push(`  const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(`)
lines.push(`    { size = 24, strokeWidth: _strokeWidth, absoluteStrokeWidth: _absolute, ...rest },`)
lines.push(`    ref`)
lines.push(`  ) {`)
lines.push(`    return (`)
lines.push(`      <svg ref={ref} xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" width={size} height={size} fill="currentColor" aria-hidden="true" {...rest}>`)
lines.push(`        {paths.map((d, index) => <path key={index} d={d} />)}`)
lines.push(`      </svg>`)
lines.push(`    )`)
lines.push(`  })`)
lines.push(`  Icon.displayName = name`)
lines.push(`  return Icon`)
lines.push(`}`)
lines.push(``)
lines.push(`/** Brand marks are not in Material Symbols; these keep Lucide's stroke drawings (ISC). */`)
lines.push(`function stroke(name: string, nodes: Array<[string, Record<string, string | number>]>) {`)
lines.push(`  const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(`)
lines.push(`    { size = 24, strokeWidth = 2, absoluteStrokeWidth: _absolute, ...rest },`)
lines.push(`    ref`)
lines.push(`  ) {`)
lines.push(`    return (`)
lines.push(`      <svg ref={ref} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={size} height={size} fill="none" stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...rest}>`)
lines.push(`        {nodes.map(([tag, attrs], index) => {`)
lines.push(`          const Tag = tag as "path"`)
lines.push(`          return <Tag key={index} {...attrs} />`)
lines.push(`        })}`)
lines.push(`      </svg>`)
lines.push(`    )`)
lines.push(`  })`)
lines.push(`  Icon.displayName = name`)
lines.push(`  return Icon`)
lines.push(`}`)
lines.push(``)

const names = Object.keys(map.symbols).sort()
for (const name of names) {
  const file = path.join(symbolsDir, `${map.symbols[name]}.svg`)
  if (!fs.existsSync(file)) {
    console.error(`No Material symbol "${map.symbols[name]}" for ${name}`)
    process.exit(1)
  }
  const svg = fs.readFileSync(file, "utf8")
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1])
  if (paths.length === 0) {
    console.error(`No path data in ${file}`)
    process.exit(1)
  }
  lines.push(`export const ${name} = symbol(${JSON.stringify(name)}, ${JSON.stringify(paths)})`)
}

lines.push(``)
for (const name of Object.keys(map.brands).sort()) {
  const file = path.join(lucideDir, `${map.brands[name]}.js`)
  const source = fs.readFileSync(file, "utf8")
  const nodes = []
  for (const match of source.matchAll(/\[\s*"(\w+)"\s*,\s*\{([^}]*)\}\s*\]/g)) {
    const attrs = {}
    for (const attr of match[2].matchAll(/(\w+)\s*:\s*"([^"]*)"/g)) {
      if (attr[1] === "key") continue
      attrs[attr[1]] = attr[2]
    }
    nodes.push([match[1], attrs])
  }
  if (nodes.length === 0) {
    console.error(`No drawing found in ${file}`)
    process.exit(1)
  }
  lines.push(`export const ${name} = stroke(${JSON.stringify(name)}, ${JSON.stringify(nodes)})`)
}
lines.push(``)

const output = lines.join("\n")
for (const app of apps) {
  const target = path.join(root, "apps", app, "components", "icons", "index.tsx")
  fs.mkdirSync(path.dirname(target), { recursive: true })
  fs.writeFileSync(target, output)
  console.log(`wrote ${path.relative(root, target)} (${names.length} symbols, ${Object.keys(map.brands).length} brands)`)
}

function walk(dir, visit) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === ".next" || entry.name.startsWith(".")) continue
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) walk(full, visit)
    else if (/\.(tsx?|jsx?)$/.test(entry.name)) visit(full)
  }
}
