import type { GoalNodeInsert, BreakdownLevelConfig, BreakdownTargets } from '@/types/goals'

/**
 * Converts JSONB breakdown_config + breakdown_targets into GoalNodeInsert[] rows
 * with correct parent-child relationships.
 *
 * Rules:
 * - All migrated nodes get allocation_mode = 'absolute'
 * - dimension_type from breakdownConfig[].label
 * - reference_field from breakdownConfig[].field
 * - Top-level keys → root nodes, nested keys → children
 * - Idempotent: same input → same output (deterministic ordering)
 */
export function transformBreakdownToNodes(
  goalId: string,
  companyId: string,
  breakdownConfig: BreakdownLevelConfig[],
  breakdownTargets: BreakdownTargets
): GoalNodeInsert[] {
  const nodes: GoalNodeInsert[] = []

  if (!breakdownConfig.length || !breakdownTargets) return nodes

  function processLevel(
    targets: BreakdownTargets,
    levelIndex: number,
    parentNodeId: string | null,
    sortStart: number
  ): void {
    if (levelIndex >= breakdownConfig.length) return

    const config = breakdownConfig[levelIndex]
    const keys = Object.keys(targets).sort() // deterministic ordering

    keys.forEach((key, idx) => {
      const entry = targets[key]
      if (!entry || typeof entry !== 'object') return

      const targetAmount = typeof entry._target === 'number' ? entry._target : 0

      // Generate a deterministic ID placeholder — the actual UUID is generated by the DB.
      // For parent_node_id linking, we use the index in the nodes array.
      const nodeIndex = nodes.length

      const node: GoalNodeInsert = {
        goal_id: goalId,
        parent_node_id: parentNodeId,
        name: key,
        dimension_type: config.label,
        reference_field: config.field,
        reference_value: key,
        allocation_mode: 'absolute',
        percentage: null,
        target_amount: targetAmount,
        monthly_targets: null,
        sort_order: sortStart + idx,
        company_id: companyId,
      }

      nodes.push(node)

      // Process nested children (keys other than _target that are objects)
      if (levelIndex + 1 < breakdownConfig.length) {
        const childTargets: BreakdownTargets = {}
        for (const [childKey, childVal] of Object.entries(entry)) {
          if (childKey === '_target') continue
          if (childVal && typeof childVal === 'object' && '_target' in childVal) {
            childTargets[childKey] = childVal as BreakdownTargets[string]
          }
        }

        if (Object.keys(childTargets).length > 0) {
          // For migration output, parent_node_id will be null since we don't have real UUIDs yet.
          // The caller is responsible for assigning IDs after insert.
          // We use a sentinel format to indicate the parent index.
          processLevel(childTargets, levelIndex + 1, `__idx:${nodeIndex}`, 0)
        }
      }
    })
  }

  processLevel(breakdownTargets, 0, null, 0)

  // Resolve __idx: references to maintain structural relationships.
  // Since we don't have real UUIDs (DB generates them), we keep the index-based
  // references so the caller can map them after batch insert.
  // For idempotency, the output is always the same for the same input.

  return nodes
}
