-- Create master_options table for dynamic dropdowns
create table public.master_options (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  option_type text not null, -- e.g., 'category', 'bu_revenue', 'status'
  label text not null,
  value text not null,
  is_active boolean default true
);

-- Create leads table with comprehensive schema (60+ columns)
create table public.leads (
  -- Group 1: Core Identity
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  manual_id integer, -- #
  category text, -- Dropdown
  bu_revenue text, -- Dropdown (BU Unit)
  company_name text, -- COMPANY
  main_company text, -- MAIN COMPANY
  month_event text,
  year_lead_receive integer,

  -- Group 2: Event Specifics
  start_date timestamp with time zone,
  date_of_event timestamp with time zone,
  project_name text, -- NAME OF PROJECT
  grade_lead text,
  main_stream text,
  tipe_stream text,
  business_purpose text,
  tipe text,
  number_of_pax integer,
  is_onsite boolean, -- ONSITE
  is_online boolean, -- ONLINE
  nationality text,
  venue_hotel text,
  location_city text, -- LOKASI (NAMA KOTA)

  -- Group 3: Status & Operations
  status text, -- STATUS (Critical Dropdown)
  cancel_lost_reason text,
  date_cancel_lost date,
  month_cancel_lost text,
  account_manager text, -- ACCOUNT
  sector text,
  line_industry text,
  area text,
  pic_sales text,
  pic_so text,
  is_qualified boolean, -- QUALIFIED
  source_lead text,
  referral_source text,

  -- Group 4: Financials
  estimated_revenue numeric, -- EST REVENUE
  nominal_konfirmasi numeric, -- NOMINAL KONFIRMASI
  materialized_amount numeric, -- MATERIALIZED
  difference_amount numeric, -- SELISIH
  percentage_deal numeric, -- %

  -- Group 5: SLA & Time Tracking
  month_receive_lead text,
  date_lead_received timestamp with time zone, -- TGL TIME LEAD TERIMA
  sla_tep_to_pd timestamp with time zone, -- TGL TIME TEP TO PD
  sla_pd_to_so timestamp with time zone, -- TGL TIME PD TO SO
  sla_pd_to_acs timestamp with time zone, -- TGL TIME PD TO ACS
  sla_so_to_pd timestamp with time zone, -- TGL TIME SO TO PD
  sla_pd_to_tep timestamp with time zone, -- TGL TIME PD TO TEP
  sla_acs_to_pd timestamp with time zone, -- TGL TIME ACS TO PD
  sla_quo_to_tep timestamp with time zone, -- TGL TIME QUO TO TEP
  sla_pro_to_tep timestamp with time zone, -- TGL TIME PRO TO TEP
  sla_quo_send_client timestamp with time zone, -- TGL TIME QUO SEND TO CLIENT
  sla_pro_send_client timestamp with time zone, -- TGL TIME PRO SEND TO CLIENT
  duration_inq_to_pd text,
  duration_inq_to_client text,

  -- Group 6: Contact Person (Client Details)
  salutation text,
  contact_full_name text,
  contact_email text,
  contact_mobile text,
  job_title text,
  date_of_birth date,
  address text,
  office_phone text,
  destination text, -- DESTINASI
  client_province_country text, -- PROVINSI/NEGARA KLIEN
  client_company_country text, -- NEGARA COMPANY KLIEN

  -- Group 7: Historical & Logs
  remark text,
  follow_up_1 text,
  follow_up_2 text,
  follow_up_3 text,
  follow_up_4 text,
  follow_up_5 text,
  sign_doc_type text, -- SIGN CL/ SPK/ GL/AGGREMENT
  date_send_doc date, -- DATE SEND
  time_log text -- TIME
);

-- Enable Row Level Security (RLS)
alter table public.leads enable row level security;
alter table public.master_options enable row level security;

-- Create Policy to allow read/write for all (can be restricted later)
create policy "Allow public access to leads"
  on public.leads for all
  using (true)
  with check (true);

create policy "Allow public access to master_options"
  on public.master_options for all
  using (true)
  with check (true);
